auth merge will be #106
Gaepo-transcendance-fighters/FRONT-END pull request #115
Opened 2023-08-31 13:03 UTC by wochae

2차 인증 로직이 데브에 없어서 피알 올립니다.
최신 데브와 106 브랜치 비교해서 파일 수정, 추가했습니다.
게임 소켓은 주석처리했습니다. 이로써 롤백 현상은 다시 나타나지 않습니다.
2차 인증 또는 닉네임 변경 시 채팅 모듈 인메모리 유저리스트 동기화를 시키는 이벤트 요청을 추가했고
2차 인증 활성화 유저가 로그인 시 2차 인증 메일 모달로 이동해서 유효 검사를 진행합니다.
106 브랜치랑 데브와 api 차이가 있어 수정하였고, 실행 결과 문제 없습니다.

2023-09-01 03:10 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +    fetch();
`fetch();` 이 부분은 필요없는건가요?

2023-09-01 03:25 UTC, joonseong11 commented
시리님 이 작업하신 pr이 아직 머지가 안된 상태인데 그 작업물과 2차인증 부분이 겹치는걸까요?

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
Number() : 문자열을 숫자로 변환한다.

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
idx 문자열을 숫자로 변환하고 다시 문자열로 변환하는것같은데, 그럼 `formData.append("userIdx", localStorage.getItem("idx").toString());` 이렇게 작성해도 되지않나요? 이렇게 작성하면 문제점이 있나요?

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +        method: "POST",
post - 생성, put - 수정

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +        method: "POST",
put에서 post로 바뀐 이유가 뭔가요??

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +        socket.emit('set_user_status', {userStatus:{ nickname: response.data.nickname}});
`response.data.result.nickname`은 바뀐 닉네임이고, `response.data.nickname`은 무슨 닉네임인가요 ?

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/app/secondauth/page.tsx
> +  const [block, setBlock] = useState<boolean>(false);
2차인증 여부에 따라 버튼 비활성화하는데에 쓰임

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/components/main/friend_list/FriendProfile.tsx
> +  const addFriend = async () => { // 이거 안 쓰는 건가요? ws
FriendProfile에선 사용안하고, MemberModal에서 사용합니다

2023-09-01 03:26 UTC, jnkeniaem commented on frontend/components/main/friend_list/FriendProfile.tsx
> +  const handleOpenNdataModal = () => {
handleOpenNdataModal에서 N은 뭘 의미하나욤 ?

2023-09-01 03:32 UTC, jnkeniaem commented on frontend/components/main/myprofile/SecondAuth.tsx
> +  }, []);
비슷한 내용 frontend/app/mypage/page.tsx에도 있는데, 여기에도 또 있는 이유가 뭔가용?

2023-09-01 03:32 UTC, jnkeniaem commented on frontend/components/main/myprofile/SecondAuth.tsx
> +      location.reload();
location.reload() 새로고침버튼처럼 현재 리소스를 다시 불러온다

2023-09-01 04:41 UTC, wochae commented on frontend/app/mypage/page.tsx
> +    fetch();
그 위에 정의된 fetch 함수가 있습니다!
롤백 될 때 요청 문제인줄 알고 바꾼거라
리팩토링이 필요해요

2023-09-01 04:43 UTC, wochae commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
그러면 userIdx string이 되서 백엔드에서 받을 때 못 읽을 것 같습니다

2023-09-01 04:43 UTC, wochae commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
getItem 반환값이 원래 string이지 않나요??

2023-09-01 04:45 UTC, wochae commented on frontend/app/mypage/page.tsx
> +        method: "POST",
시리님이랑 작업할 때 
닉네임을 바꿀꺼면 imgData를 빈 문자열로, 이미지를 바꿀꺼면 닉네임을 빈 문자열로 보내서 백엔드에 같은 함수가 처리하도록 설계했습니다!

2023-09-01 04:49 UTC, wochae commented on frontend/app/mypage/page.tsx
> +        socket.emit('set_user_status', {userStatus:{ nickname: response.data.nickname}});
밑에 속성은 사용하지 않습니다.
백엔드에서 어떻게 받는지 확인하려고 요청 파라미터를 맞추려다가 남겨진 것 같습니다.

현재 서버 채팅 유저 인메모리는 데이터베이스에 최신 정보를 불러와서 동기화 합니다.

2023-09-01 04:49 UTC, wochae commented on frontend/components/main/friend_list/FriendProfile.tsx
> +  const addFriend = async () => { // 이거 안 쓰는 건가요? ws
어쩐지 회색이더라구요

2023-09-01 04:52 UTC, wochae commented on frontend/components/main/friend_list/FriendProfile.tsx
> +  const handleOpenNdataModal = () => {
최신 작업에 저걸 정의해서 사용하길래 남겨뒀습니다! 작성자 확인해볼게요

2023-09-01 05:03 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
네 문자열 반환합니다.

2023-09-01 05:04 UTC, jnkeniaem commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
`Number(localStorage.getItem("idx")).toString()` 이 코드는 Number(문자열).toString(). 그니까, 문자열을 숫자로 변환한 후 다시 문자열로 변환하는 것같아서, 이러면 그냥 append 두번째 인자에 `localStorage.getItem("idx")` < 이것만 작성해도 되지 않나 싶어서요 !

2023-09-01 05:08 UTC, wochae commented
> 시리님 이 작업하신 pr이 아직 머지가 안된 상태인데 그 작업물과 2차인증 부분이 겹치는걸까요?

네 그 브랜치는 dev랑 오토 머지가 안 되는데, 시리님 코드 이후로 호슬림님이랑 추가로 작업한 게 있는데
수동 충돌 해결로 하려고 하면 그 작업이 누락될 것 같아서 브랜치에 맞게 새로 올렸습니다.

2023-09-01 05:36 UTC, wochae reviewed
추가 답변

2023-09-01 05:36 UTC, wochae commented on frontend/components/main/myprofile/SecondAuth.tsx
> +  }, []);
원래는 코드로 사용하다가 컴포넌트로 빼서 쓰는 것 같은데, 둘 다 노란색으로 사용하고 있길래 유지했습니다.

2023-09-01 05:36 UTC, wochae commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
아 맞아요! 그렇게 할게요

2023-09-01 05:36 UTC, wochae commented on frontend/components/main/friend_list/FriendProfile.tsx
> +  const handleOpenNdataModal = () => {
8/25 시리님이 작성한 코드에요

2023-09-01 05:36 UTC, wochae commented on frontend/components/main/myprofile/SecondAuth.tsx
> +  }, []);
컴포넌트로 빼서 mypage/page.tsx 에서 사용하고 있는거 맞네요

2023-09-01 05:36 UTC, wochae commented on frontend/app/mypage/page.tsx
> +    formData.append("userIdx", Number(localStorage.getItem("idx")).toString());
아 잘못 알았네요 formData ( key : value ) 에서 value 타입은는 string | blob 인데 
localStorage.getItem() 반환은 string | null  널이 들어올 수 있어서 형변환을 해야할 것 같아요. 
아니면, 이걸로 바꾸는건 어떤가요
```js
localStorage.getItem("idx") || ""
```

2023-09-01 05:54 UTC, jnkeniaem approved these changes
lgtm 고생하셨습니다!

2023-09-03 03:55 UTC, HiHoi approved these changes
LGTM! 정말 수고하셨습니다

2023-09-03 04:09 UTC, HiHoi requested changes

2023-09-03 04:09 UTC, HiHoi commented on frontend/app/optionselect/page.tsx
여기 주석 처리 풀어주세요

2023-09-03 04:12 UTC, joonseong11 requested changes

2023-09-03 04:12 UTC, joonseong11 commented on frontend/components/main/friend_list/FriendProfile.tsx
>      const userProfile = (data: IFriendData) => {
userProfile도 있고 UserProfile도 있어요 중복코드!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@SihunLee-1016 @wochae

2023-09-03 04:12 UTC, joonseong11 commented on frontend/app/optionselect/page.tsx
game optionselect 페이지 주석되어있어여!!!!!!!!!!!!!!!!!!!!1

2023-09-03 04:12 UTC, joonseong11 commented on frontend/app/mypage/page.tsx
> +  imgData: any;
데이터 타입 any 고쳐야돼요!

2023-09-03 04:44 UTC, wochae commented on frontend/app/mypage/page.tsx
> +  imgData: any;
근데 이거 안 쓰고 있던데 ㅠw

2023-09-03 05:28 UTC, wochae reviewed
반영

2023-09-03 05:52 UTC, joonseong11 approved these changes

2023-09-03 05:53 UTC, wochae reviewed
반영!

2023-09-03 06:00 UTC, HiHoi approved these changes
LGTM 정말 수고하셨습니다!

2023-09-03 06:00 UTC, merged