95번 게임 브랜치 2차 합병
Gaepo-transcendance-fighters/FRONT-END pull request #155
Opened 2023-09-11 06:25 UTC by HiHoi

진행 상황

- 게임 접속 가능
- 변경된 로직 적용
- 패들 움직임
- 가시성 향상
- 공 튕김

추가해야할 부분

- 게임 종료 부분
- 유저 disconnect
- 배고픔
- 동시 접속시 큐에 제대로 안 담김

2023-09-15 08:54 UTC, HiHoi commented
@jnkeniaem @joonseong11 지금까지 작업한 거 PR 올립니다.

2023-09-15 09:38 UTC, joonseong11 requested changes

2023-09-15 09:38 UTC, joonseong11 commented on frontend/components/game/ingame/PingPong.tsx
> +      setKeyboard(0);
왜 업 다운 둘다 0 인가요?

2023-09-15 09:38 UTC, joonseong11 commented on frontend/components/game/ingame/PingPong.tsx
> +    authState.gameSocket.on(
이부분은 무의미한 코드인가요?

2023-09-15 09:39 UTC, HiHoi commented on frontend/components/game/ingame/PingPong.tsx
> +      setKeyboard(0);
이 부분은 키보드를 떼는 부분이라 0을 의도적으로 넣는 겁니다.

2023-09-15 09:40 UTC, HiHoi commented on frontend/components/game/ingame/PingPong.tsx
> +    authState.gameSocket.on(
아직 테스트 중입니다!

2023-09-15 09:57 UTC, joonseong11 commented on frontend/components/game/ingame/PingPong.tsx
> +      setKeyboard(0);
이부분이 잘 이해가 안되는디 좀더 로직을 자세히 설명해줄 수 잇을까요?

2023-09-15 10:01 UTC, HiHoi commented on frontend/components/game/ingame/PingPong.tsx
> +      setKeyboard(0);
키보드의 액션은 누르는 것과 떼는 것이 있습니다 누를때는 상하에 맞게 숫자를 넣어야하지만 떼는 경우에 다시 0으로 초기화를 해줘야 서버에서 주기적으로 데이터를 보낼 때 0을 제대로 보내줄 수 있습니다

2023-09-15 11:49 UTC, joonseong11 approved these changes

2023-09-15 11:49 UTC, joonseong11 commented on frontend/components/game/ingame/PingPong.tsx
> +      setKeyboard(0);
액션을 누르는 부분은 예전 pr 에서봤떤거 같은데 이번 pr 에는 변경되지 않아서 보이지 않는 것이었군요 잘봤습니다

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/gameplaying/page.tsx
> +
type.tsx 같은 타입 파일에 넣어주세요~!

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/inwaiting/page.tsx
> +    authState.gameSocket.on("game_queue_quit", () => {});
이 부분은 아직 작업 중 인가요?

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/game/friend/optionselect/page.tsx
> +  if (!client) return <></>;
이 경우엔 컴포넌트를 아무것도 안띄워주는건가요?
근데 setClient가 false인 경우도 있을까요? 있다면 어떤 경우인가요?

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/gameplaying/page.tsx
> +    authState.gameSocket.on("game_force_quit", (msg: string) => {
game_force_quit emit 하는 부분이 안보이는데 broadcasting인가요?

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/inwaiting/page.tsx
> +    window.addEventListener("popstate", preventGoBack);
popstate는 뒤로가기나 앞으로가기 버튼을 클릭했을때 이벤트가 트리거

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/app/optionselect/page.tsx
> +import axios from "axios";
이 파일이랑 frontend/app/game/friend/optionselect/page.tsx 이거랑 내용 비슷한것같은데 어떤 경우에 해당 경로에 접속하나요?

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/components/game/ingame/PingPong.tsx
> +        data.gameStatus === EGameStatus.JUDGE
EGameStatus.JUDGE는 어떤 경우인가요?

2023-09-16 14:13 UTC, jnkeniaem commented on frontend/components/game/ingame/PingPong.tsx
> +      authState.gameSocket!.emit(
data.gameStatus === EGameStatus.ONGOING 일때 game_pause_score on을 하는 경우는 게임 플레이 중에 상대방이 나갈때 일까요?

2023-09-17 02:58 UTC, HiHoi commented on frontend/app/inwaiting/page.tsx
> +    authState.gameSocket.on("game_queue_quit", () => {});
단순 이벤트 등록부라 익명함수로 대체했습니다.

2023-09-17 02:59 UTC, HiHoi commented on frontend/app/game/friend/optionselect/page.tsx
> +  if (!client) return <></>;
이 부분은 순수 클라이언츠 렌더링을 위한 트릭입니다. next.js 특성상 틈만 나면 서버로 렌더링하는 친구라 평가때 SPA를 증명하기 위해서 useEffect라는 클라이언트 상태에서 렌더링을 일부러 시키는 겁니다.

2023-09-17 03:00 UTC, HiHoi commented on frontend/app/gameplaying/page.tsx
> +    authState.gameSocket.on("game_force_quit", (msg: string) => {
게임 당사자 끼리만 서버쪽에서 신호를 주면 받아서 처리하는 부분입니다.

2023-09-17 03:01 UTC, HiHoi commented on frontend/app/optionselect/page.tsx
> +import axios from "axios";
친선전 테스트 중 if 조건문으로 게임의 타입에 따라 행동을 달리 주려고 했는데 잘 먹히지 않아서 페이지를 한번 나눌려고 했습니다. qa가 끝나면 삭제되거나 사용될 페이지입니다.

2023-09-17 03:01 UTC, HiHoi commented on frontend/components/game/ingame/PingPong.tsx
> +        data.gameStatus === EGameStatus.JUDGE
상대가 나가거나 네트워크 상태가 좋지 않을 경우에 대한 판정승에 대한 부분입니다.

2023-09-17 03:03 UTC, HiHoi commented on frontend/components/game/ingame/PingPong.tsx
> +      authState.gameSocket!.emit(
ongoing은 진행중이라는 의미로 게임의 정상적인 스코어 행위에 대한 행동입니다. 상대가 나가면 judge로 판정승 처리를 합니다.

2023-09-17 03:23 UTC, jnkeniaem approved these changes
정말 고생많으셨습니다!!!
전에도 몇번 말씀드렸는데 리뷰할때 코드량이 많아 리뷰하는게 쉽지 않아요ㅠ 다음 pr이 있으면 꼭 쪼개서 올려주세요 !
+타입관련된거 다 타입 파일에 넣어주시와요

2023-09-17 04:09 UTC, merged

2023-09-17 06:12 UTC, joonseong11 commented on frontend/components/main/InviteGame/InviteGame.tsx
> +    // const recieveInvite = ({
여기 주석은 아직 테스트 부분인가유?

2023-09-17 06:12 UTC, joonseong11 commented on frontend/components/game/ingame/WaterBomb.tsx
크으으으 워터밤 최고!