45 refactor context api
Gaepo-transcendance-fighters/FRONT-END pull request #50
Opened 2023-08-04 06:25 UTC by HiHoi

## 공통사항
useReducer 사용

1. 방 목록 리스트 추가
2. 방 멤버 리스트 추가
3. 로그인 관련 로직 추가
4. 사용자 정보 추가

2023-08-04 06:31 UTC, jnkeniaem approved these changes
lgtm

2023-08-07 06:07 UTC, SihunLee-1016 approved these changes
LGTM!

2023-08-07 06:31 UTC, joonseong11 requested changes
현재 열고잇는 방과 방멤버를 받아오는군여! 잘봣습니다!

2023-08-07 06:31 UTC, joonseong11 commented on frontend/hooks/useRequireAuth.ts
> +  const { state } = useAuth();
state를 객체화 시켜 useAuth() 리턴을 할당하는 건가유?
state에다가 {} 괄호를 넣어서 할당하는건 낯설어서 여쭤봐유!

2023-08-07 06:34 UTC, joonseong11 commented on frontend/hooks/useRequireAuth.ts
> +  const { state } = useAuth();
해결되었습니다!

2023-08-07 06:39 UTC, joonseong11 approved these changes
잘 봤습니다!

2023-08-07 06:39 UTC, merged