75 main chat 05 api 멤버 우클릭시 드롭다운인 set/unset admin, kick, ban, mute ap
Gaepo-transcendance-fighters/FRONT-END pull request #81
Opened 2023-08-18 07:41 UTC by jnkeniaem

멤버 우클릭시 드롭다운인 set/unset admin, kick, ban, mute ap

- 필요없는 코드 삭제
- css class 추가
- 변경/ 완성된 mute, kick, ban, admin api 적용
- 관리자에게 별테두리 아이콘 붙임
- 본인과 채널 owner는 우클릭시 드롭다운 안보이게함
- 이제 admin 배열 받기 때문에 chat_get_grant 부분 필요없을것같은데 혹시 몰라 주석처리해놓음
- localStorage에 user idx, user nickname 저장해놓고 이걸로 socket 만들고, main_enter_0때 socket.emit() 때 사용.
- 그리고 socket.emit() 두번째 인자 상수로 보냈던거 다 저장데이터 사용하는 식으로 변경
- Layout.tsx와 내가 작성한 파일들에 있는 타입들 모두 type.tsx파일에 모아둠
- chat_goto_lobby 적용 !dm 방에서 public/protected 방 들어갈때
- 들어가있는 방 다시 방 목록에서 클릭하면 아무런 처리 안되게 함
-[] 맨 처음엔 잘 적용됐는데, ex) 1번방 있다가 2번방 들어갔을때 2번방 버튼 계속 누르면 계속 들어가는 로직 작동돼서 다음 pr때 막아야 함...
- 서버로부터 받는 admin 배열 room쪽 전역변수로 관리
- 어떤 방 성공적으로 들어가면 방 목록에서 그 방은 색이 바뀜
- 방에 0명 남으면 지워주는 api 적용
- admin이면 메뉴 3개만 보이게 함. (owner는 4개 보임)
- main 타입 사용한 부분에서 경로 변경해줌
- 토큰 받을때 받는 유저 데이터를 userState로 저장해봤지만, 처음 메인화면 접속시 문제 없는데, 새로고침했을때 다 날라가서 localStorage 쓰는게 나을것같아서 다시 돌립
- socket.emit했을때 서버에서 return 하는 데이터 ret로, socket.on했을때 받는 데이터는 payload로 이름 변경

2023-08-18 07:57 UTC, SihunLee-1016 commented on frontend/components/main/chat_window/BottomField/BottomField.tsx
> +        senderIdx: 98364,
임의지정값인가요?!

2023-08-18 09:20 UTC, jnkeniaem commented on frontend/components/main/chat_window/BottomField/BottomField.tsx
> +        senderIdx: 98364,
네. 주전님파트라 주전님이 고쳐주실겁니당

2023-08-18 09:23 UTC, SihunLee-1016 approved these changes
확인했습니다! payload나중에 설명해주세요~!

2023-08-18 09:41 UTC, HiHoi commented on frontend/components/public/Layout.tsx
> +          if (ret === 200) {
이 부분은 나중에 추가해야할 부분인가요?

2023-08-19 05:22 UTC, jnkeniaem commented on frontend/components/public/Layout.tsx
> +          if (ret === 200) {
네 지금은 다 성공케이스로 하고 있어서 실패 경우는 성공 케이스 다 되고 일괄적으로 처리해야합니다

2023-08-19 05:34 UTC, joonseong11 requested changes

2023-08-19 05:34 UTC, joonseong11 commented on frontend/context/RoomContext.tsx
> +  | { type: "SET_CUR_DM_MEM"; value: IDmMemList }
왜 ADD_CUR_MEM 를 삭제하였나요? SET_CUR_MEM로 충분해서?

2023-08-19 05:34 UTC, joonseong11 commented on frontend/context/RoomContext.tsx
> +  | { type: "SET_ADMIN_ARY"; value: { nickname: string }[] };
왜 ADMIN ARY를 추가하였나요?

2023-08-19 05:34 UTC, joonseong11 commented on frontend/components/main/room_list/Room.tsx
> +    if (roomState.currentRoom != room) {
이부분이 같은 채널을 여러번 누를때도 방에 계쏙 입장되는 부분이었죠? 그때 해결하셨지만 여기선 아직 반영이 안되었나용

2023-08-19 05:34 UTC, joonseong11 commented on frontend/components/main/chat_window/BottomField/BottomField.tsx
> +        senderIdx: 98364,
넵 나중에 주전님 브랜치 머지되면 고쳐져있을겁니당

2023-08-19 05:38 UTC, jnkeniaem commented on frontend/context/RoomContext.tsx
> +  | { type: "SET_CUR_DM_MEM"; value: IDmMemList }
넹

2023-08-19 05:40 UTC, jnkeniaem commented on frontend/context/RoomContext.tsx
> +  | { type: "SET_ADMIN_ARY"; value: { nickname: string }[] };
Member.tsx, Room.tsx에서 사용하는데, 둘은 부모자식 관계가 아니라 prop drilling이 나서 전역으로 관리해주고있어여

2023-08-19 05:42 UTC, jnkeniaem commented on frontend/components/main/room_list/Room.tsx
> +    if (roomState.currentRoom != room) {
네네 다음 브랜치에서 작업했는데, 그냥 여기서 고치고 머지하기전 push 할게용

2023-08-19 05:43 UTC, jnkeniaem commented
> 확인했습니다! payload나중에 설명해주세요~!

넹~

2023-08-19 05:44 UTC, joonseong11 approved these changes
고생많았어용

2023-08-19 07:14 UTC, HiHoi approved these changes
LGTM! 정말 수고하셨습니다!

2023-08-19 07:15 UTC, merged